server:
  port: ${SPRING_SERVER_PORT:7084}
  servlet:
    context-path: /
    application-display-name: ${spring.application.name}
spring:
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: dice-game-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

kafka:
  topics:
    game-topic: game-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7081/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    health:
      enabled: true
    web:
      exposure:
        include: info, health, metrics